### PR TITLE
Agahkarakuzu patch 1

### PR DESCRIPTION
**Pull request by agahkarakuzu**

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
@agahkarakuzu  Any reason why you merged before it was tested? It could have been tested on a branch. The Binder button points to a broken link, as you don't clone this current repo in your Dockerfile. The file "demo.ipynb" doesn't exist in the built image currently.

**Comment by agahkarakuzu** [comment]
I'll revert, had to test something.

**Comment by mathieuboudreau** [comment]
No worries - any reason why you had to test on master and couldn't do so on a branch? Just curious

**Comment by agahkarakuzu** [comment]
I just noticed that the main `octjn` builds were  missing `sos-r==0.9.12.2`, the rest is the same versions with yours. 

I remembered one more important detail: varargin 2+ should be parsed as input args because the first one is always `$LD_LIBRARY_PATH` with MCR. 

I wanted to try on `master` to see if the files from the root will be fetched without `ADD`. I wanted to use `master` just as an extra measure, as I was running into build issues with branches every now and then.

**Comment by mathieuboudreau** [comment]
>I just noticed that the main octjn builds were missing sos-r==0.9.12.2, the rest is the same versions with yours.

That damn bug has been plaguing me for over a year! lol. I don't know why, but for a while it wasn't needed, and then it broke all my tutorials.

>I wanted to try on master to see if the files from the root will be fetched without ADD. I wanted to use master just as an extra measure, as I was running into build issues with branches every now and then.

Interesting - thanks for clarifying!

**Comment by agahkarakuzu** [comment]
This was a good excuse to notice that missing `sos-r`. It will be one of the fixes on `2.4.0` release.

**Pull request merged**
